//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices.Management {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.MobileServices.Management.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asynchronous Windows Azure management operation {0} failed. .
        /// </summary>
        internal static string AsyncOperationFailed {
            get {
                return ResourceManager.GetString("AsyncOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Application xmlns=&quot;http://schemas.microsoft.com/windowsazure&quot;&gt;
        ///  &lt;Name&gt;{0}&lt;/Name&gt; 
        ///  &lt;Label&gt;{1}&lt;/Label&gt;
        ///  &lt;Description&gt;{2}&lt;/Description&gt;
        ///  &lt;Configuration&gt;{3}&lt;/Configuration&gt;
        ///&lt;/Application&gt;.
        /// </summary>
        internal static string CreateMobileServiceApplicationTemplate {
            get {
                return ResourceManager.GetString("CreateMobileServiceApplicationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the default location for new Windows Azure Mobile Services..
        /// </summary>
        internal static string ErrorGettingDefaultServiceLocation {
            get {
                return ResourceManager.GetString("ErrorGettingDefaultServiceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an existing SQL database you must specify both SQL database name and SQL server name parameters as well as SQL server username and password..
        /// </summary>
        internal static string ExisingSqlDbRequiresExistingSqlServer {
            get {
                return ResourceManager.GetString("ExisingSqlDbRequiresExistingSqlServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile service management endpoint {0} is not recognized..
        /// </summary>
        internal static string InvalidManagementEndpoint {
            get {
                return ResourceManager.GetString("InvalidManagementEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login name must meet the following requirements: 1. It must be a SQL Identifier. 2. It cannot be a system name, for example: admin, administrator, sa, root, dbmanager, loginmanager, etc. 3. It cannot be a built-in database user or role like dbo, guest, public, etc. 4. It cannot contain: spaces, tabs, or returns, unicode characters, nonalphabetic characters (&quot;&lt;&gt;|:*?\/#&amp;;,%=). 5. It cannot begin with digits (0 through 9), @, $, +..
        /// </summary>
        internal static string InvalidSqlUsername {
            get {
                return ResourceManager.GetString("InvalidSqlUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete operation. Windows Azure management endpoint {0} was deprecated..
        /// </summary>
        internal static string ManagemendEndpointDeprecated {
            get {
                return ResourceManager.GetString("ManagemendEndpointDeprecated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementCertificate must contain private key..
        /// </summary>
        internal static string ManagementCertificateWithoutPrivateKey {
            get {
                return ResourceManager.GetString("ManagementCertificateWithoutPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to the Windows Azure Mobile Services management endpoint returned unexpected HTTP status code {0}..
        /// </summary>
        internal static string ManagementServiceReturnedHttpError {
            get {
                return ResourceManager.GetString("ManagementServiceReturnedHttpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementCertificate must be specified on the MobileServiceManagementClient..
        /// </summary>
        internal static string MissingManagementCertificate {
            get {
                return ResourceManager.GetString("MissingManagementCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobileServiceManagementEndpoint must be specified on the MobileServiceManagementClient..
        /// </summary>
        internal static string MissingMobileServiceManagementEndpoint {
            get {
                return ResourceManager.GetString("MissingMobileServiceManagementEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required service name parameter is not provided..
        /// </summary>
        internal static string MissingServiceName {
            get {
                return ResourceManager.GetString("MissingServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required SQL administrator password parameter is not provided..
        /// </summary>
        internal static string MissingSqlAdminPassword {
            get {
                return ResourceManager.GetString("MissingSqlAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required SQL administrator username parameter is not provided. .
        /// </summary>
        internal static string MissingSqlAdminUsername {
            get {
                return ResourceManager.GetString("MissingSqlAdminUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubscriptionId must be specified on the MobileServiceManagementClient..
        /// </summary>
        internal static string MissingSubscriptionId {
            get {
                return ResourceManager.GetString("MissingSubscriptionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to Windows Azure Mobile Services management endpoint did not return asynchronous operation ID..
        /// </summary>
        internal static string NoOperationIdInResponse {
            get {
                return ResourceManager.GetString("NoOperationIdInResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to Windows Azure Mobile Services management endpoint did not return a response..
        /// </summary>
        internal static string NoResponse {
            get {
                return ResourceManager.GetString("NoResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Creation of a mobile service failed, but some of the artifacts have been provisioned. Please refer to the Windows Azure Mobile Services management portal to inspect the status of the mobile service and/or related artifacts..
        /// </summary>
        internal static string ServiceUnhealthy {
            get {
                return ResourceManager.GetString("ServiceUnhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to obtain configuration information for Windows Azure Mobile Services management endpoints from {0}..
        /// </summary>
        internal static string UnableToAccessConfiguration {
            get {
                return ResourceManager.GetString("UnableToAccessConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to Windows Azure Mobile Services management endoint returned a response that cannot be parsed as XML: {0}.
        /// </summary>
        internal static string UnableToProcessResponse {
            get {
                return ResourceManager.GetString("UnableToProcessResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An asynchronous Windows Azure management operation returned an unrecognized status of {0}..
        /// </summary>
        internal static string UnexpectedAsyncOperationStatus {
            get {
                return ResourceManager.GetString("UnexpectedAsyncOperationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to Windows Azure Mobile Services management endoint returned an invalid response: {0}.
        /// </summary>
        internal static string UnexpectedResponse {
            get {
                return ResourceManager.GetString("UnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to the Windows Azure Mobile Services management endpoing returned unexpected response type. Expected type is {0} and actual is {1}. .
        /// </summary>
        internal static string UnexpectedTypeOfResponse {
            get {
                return ResourceManager.GetString("UnexpectedTypeOfResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified SQL administrator password does not meet strength requirements. The password must be at least 8 characters long, cannot contain the SQL administrator username, and must contain at least three of the following types of characters: uppercase letter, lowercase letter, digit, non-alphanumeric character..
        /// </summary>
        internal static string WeakSqlAdminPassword {
            get {
                return ResourceManager.GetString("WeakSqlAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL administrator password does not meet strength requirements. SQL administrator password must be at least 8 characters long, not contain the SQL administrator username, and contain characters from at least 3 of the following classes of characters: uppercase letter A-Z, lowercase letter a-z, digit 0-9, and a non-alphanumeric character.  .
        /// </summary>
        internal static string WeakSqlPassword {
            get {
                return ResourceManager.GetString("WeakSqlPassword", resourceCulture);
            }
        }
    }
}
