//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.MobileServices.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Linq IQueryable Select() operation is not supported on the Windows Phone 7.5 platform..
        /// </summary>
        internal static string ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75 {
            get {
                return ResourceManager.GetString("ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is not supported in the &apos;Where&apos; Mobile Services query expression &apos;{1}&apos;..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_MemberUnsupported {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_MemberUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not supported in the &apos;Where&apos; Mobile Services query expression &apos;{1}&apos;..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_OperatorUnsupported {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_OperatorUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported in a &apos;Where&apos; Mobile Services query expression..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_UnsupportedInWhereExpression {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_UnsupportedInWhereExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All message handlers except the last must be of the type &apos;{0}&apos;.
        /// </summary>
        internal static string HttpMessageHandlerExtensions_WrongHandlerType {
            get {
                return ResourceManager.GetString("HttpMessageHandlerExtensions_WrongHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application setting name must be provided. Null, empty or whitespace only names are not allowed..
        /// </summary>
        internal static string IApplicationStorage_NullOrWhitespaceSettingName {
            get {
                return ResourceManager.GetString("IApplicationStorage_NullOrWhitespaceSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication was cancelled by the user..
        /// </summary>
        internal static string IAuthenticationBroker_AuthenticationCanceled {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_AuthenticationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed with HTTP response code {0}..
        /// </summary>
        internal static string IAuthenticationBroker_AuthenticationFailed {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of the authentication response..
        /// </summary>
        internal static string IAuthenticationBroker_InvalidLoginResponse {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_InvalidLoginResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed: {0}.
        /// </summary>
        internal static string IAuthenticationBroker_LoginFailed {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is already in progress..
        /// </summary>
        internal static string IAuthenticationBroker_LoginInProgress {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_LoginInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication has not been started..
        /// </summary>
        internal static string IAuthenticationBroker_NoLoginInProgress {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_NoLoginInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null, empty or only whitespace..
        /// </summary>
        internal static string MobileServiceClient_EmptyArgument {
            get {
                return ResourceManager.GetString("MobileServiceClient_EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be completed.  ({0}).
        /// </summary>
        internal static string MobileServiceClient_ErrorMessage {
            get {
                return ResourceManager.GetString("MobileServiceClient_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;InnerHandler&apos; property of the delegating handler must be null..
        /// </summary>
        internal static string MobileServiceClient_InnerHandlerMustBeNull {
            get {
                return ResourceManager.GetString("MobileServiceClient_InnerHandlerMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not provide a response with the expected content..
        /// </summary>
        internal static string MobileServiceClient_NoResponseContent {
            get {
                return ResourceManager.GetString("MobileServiceClient_NoResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to incrementally load more items of type &apos;{0}&apos;. See the inner exception for details..
        /// </summary>
        internal static string MobileServiceCollection_IncrementalLoadingFailed {
            get {
                return ResourceManager.GetString("MobileServiceCollection_IncrementalLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of more items already in process..
        /// </summary>
        internal static string MobileServiceCollection_LoadInProcess {
            get {
                return ResourceManager.GetString("MobileServiceCollection_LoadInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has an integer id member and therefore can not have any members with the system property attribute &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; member found on type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_MemberNotFound {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member can only have one system property attribute. The member &apos;{0}&apos; on type &apos;{1}&apos; has system property attributes &apos;{2}&apos; and &apos;{3}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_MultipleSystemPropertyAttributes {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_MultipleSystemPropertyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for member {1} is outside the valid range for numeric columns..
        /// </summary>
        internal static string MobileServiceContractResolver_NumberOutOfRange {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_NumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one member may have the property name &apos;{0}&apos; (regardless of casing) on type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_SamePropertyName {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_SamePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a DataContractAttribute, but the type derives from the type &apos;{1}&apos;, which does have a DataContractAttribute. If a type has a DataContractAttribute, any type that derives from that type must also have a DataContractAttribute..
        /// </summary>
        internal static string MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has one or members with a DataMemberAttribute, but the type itself does not have a DataContractAttribute. Use the Newtonsoft.Json.JsonPropertyAttribute in place of the DataMemberAttribute and set the PropertyName to the desired name..
        /// </summary>
        internal static string MobileServiceContractResolver_TypeWithDataMemberButNoDataContract {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_TypeWithDataMemberButNoDataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}.ContractResolver&apos; must be set to an instance of the &apos;{1}&apos; class or a class that inherits from the &apos;{1}&apos; class..
        /// </summary>
        internal static string MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver {
            get {
                return ResourceManager.GetString("MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not support reading JSON..
        /// </summary>
        internal static string MobileServicePrecisionCheckConverter_ReadNotSupported {
            get {
                return ResourceManager.GetString("MobileServicePrecisionCheckConverter_ReadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a login operation because login is already in progress..
        /// </summary>
        internal static string MobileServicesAuthentication_LoginAlreadyInProgress {
            get {
                return ResourceManager.GetString("MobileServicesAuthentication_LoginAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The casing of the &apos;{0}&apos; property is invalid..
        /// </summary>
        internal static string MobileServiceSerializer_IdCasingIncorrect {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdCasingIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} member not found..
        /// </summary>
        internal static string MobileServiceSerializer_IdNotFound {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might be affected by Mobile Services latest changes to support string Ids. For more details: http://go.microsoft.com/fwlink/?LinkId=330396.
        /// </summary>
        internal static string MobileServiceSerializer_IdTypeMismatch {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer id &apos;{0}&apos; is not a positive integer value..
        /// </summary>
        internal static string MobileServiceSerializer_InvalidIntegerId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_InvalidIntegerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string id &apos;{0}&apos; is invalid. An id must not contain any control characters or the characters &quot;,+,?,\,/,`..
        /// </summary>
        internal static string MobileServiceSerializer_InvalidStringId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_InvalidStringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id parameter type &apos;{0}&apos; is invalid for looking up items of type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceSerializer_LookupInvalidIdType {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_LookupInvalidIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id can not be null or an empty string..
        /// </summary>
        internal static string MobileServiceSerializer_NullOrEmptyStringId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_NullOrEmptyStringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string id &apos;{0}&apos; is longer than the max string id length of {1} characters..
        /// </summary>
        internal static string MobileServiceSerializer_StringIdTooLong {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_StringIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id must be of type string..
        /// </summary>
        internal static string MobileServiceSyncTable_IdMustBeString {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_IdMustBeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental pull query must not have orderby clause..
        /// </summary>
        internal static string MobileServiceSyncTable_IncrementalPullWithOrderNotAllowed {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_IncrementalPullWithOrderNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremental pull query must not have skip or top specified..
        /// </summary>
        internal static string MobileServiceSyncTable_IncrementalPullWithSkipTopNotSupported {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_IncrementalPullWithSkipTopNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query id must not contain pipe character and should be less than 50 characters in length..
        /// </summary>
        internal static string MobileServiceSyncTable_InvalidQueryId {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_InvalidQueryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported table options does not include orderby..
        /// </summary>
        internal static string MobileServiceSyncTable_OrderByNotAllowed {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_OrderByNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull query with select clause is not supported..
        /// </summary>
        internal static string MobileServiceSyncTable_PullWithSelectNotSupported {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_PullWithSelectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported table options does not include skip. .
        /// </summary>
        internal static string MobileServiceSyncTable_SkipNotAllowed {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_SkipNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supported table options does not include top..
        /// </summary>
        internal static string MobileServiceSyncTable_TopNotAllowed {
            get {
                return ResourceManager.GetString("MobileServiceSyncTable_TopNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete if the {0} member is set to a default value..
        /// </summary>
        internal static string MobileServiceTable_DeleteWithoutId {
            get {
                return ResourceManager.GetString("MobileServiceTable_DeleteWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get an array from response {0}..
        /// </summary>
        internal static string MobileServiceTable_ExpectedArray {
            get {
                return ResourceManager.GetString("MobileServiceTable_ExpectedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert if the {0} member is already set..
        /// </summary>
        internal static string MobileServiceTable_InsertWithExistingId {
            get {
                return ResourceManager.GetString("MobileServiceTable_InsertWithExistingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not found in local store..
        /// </summary>
        internal static string MobileServiceTable_ItemNotFoundInStore {
            get {
                return ResourceManager.GetString("MobileServiceTable_ItemNotFoundInStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get object from response {0}..
        /// </summary>
        internal static string MobileServiceTable_NotSingleObject {
            get {
                return ResourceManager.GetString("MobileServiceTable_NotSingleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query uri must be on the same host as the Mobile Service..
        /// </summary>
        internal static string MobileServiceTable_QueryUriHostIsDifferent {
            get {
                return ResourceManager.GetString("MobileServiceTable_QueryUriHostIsDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update if the {0} member is set to a default value..
        /// </summary>
        internal static string MobileServiceTable_UpdateWithoutId {
            get {
                return ResourceManager.GetString("MobileServiceTable_UpdateWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation must have an item associated with it..
        /// </summary>
        internal static string MobileServiceTableOperation_ItemNotFound {
            get {
                return ResourceManager.GetString("MobileServiceTableOperation_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Service table operation returned an unexpected response..
        /// </summary>
        internal static string MobileServiceTableOperation_ResultNotJObject {
            get {
                return ResourceManager.GetString("MobileServiceTableOperation_ResultNotJObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized query parameter &apos;{0}&apos;..
        /// </summary>
        internal static string MobileServiceTableQueryDescription_UnrecognizedQueryParameter {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryDescription_UnrecognizedQueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Mobile Services query expressions must consist of members only, not &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_MembersOnlyInExpression {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_MembersOnlyInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Mobile Services query expressions must consist of a single integer, not &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_SingleIntegerOnly {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_SingleIntegerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{1}&apos; is not a supported &apos;{0}&apos; Mobile Services query expression..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_UnsupportedExpression {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_UnsupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize value {0} into &apos;{1}.{2}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_CannotDeserializeValue {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_CannotDeserializeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize type &apos;{0}&apos; because the JSON object did not have required member(s) &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_MissingRequiredMember {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_MissingRequiredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON object to deserialize, not &apos;{0}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_NeedObject {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_NeedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize member &apos;{0}&apos; of type &apos;{1}&apos; declared on type &apos;{2}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_UnknownType {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid user-defined query string parameter. User-defined query string parameters must not begin with a \&apos;$\&apos;..
        /// </summary>
        internal static string MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign {
            get {
                return ResourceManager.GetString("MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;&apos;)&apos; or &apos;,&apos; expected..
        /// </summary>
        internal static string ODataExpressionParser_CloseParenOrCommaExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_CloseParenOrCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; or operator expected.
        /// </summary>
        internal static string ODataExpressionParser_CloseParenOrOperatorExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_CloseParenOrOperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit expected..
        /// </summary>
        internal static string ODataExpressionParser_DigitExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_DigitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression expected..
        /// </summary>
        internal static string ODataExpressionParser_ExpressionExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;{0}&apos; requires {1} parameter(s)..
        /// </summary>
        internal static string ODataExpressionParser_FunctionArgsCount {
            get {
                return ResourceManager.GetString("ODataExpressionParser_FunctionArgsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier..
        /// </summary>
        internal static string ODataExpressionParser_IdentifierExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected integer literal..
        /// </summary>
        internal static string ODataExpressionParser_IntegerLiteralExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_IntegerLiteralExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified odata query has invalid integer literal &apos;{0}&apos;..
        /// </summary>
        internal static string ODataExpressionParser_InvalidIntegerLiteral {
            get {
                return ResourceManager.GetString("ODataExpressionParser_InvalidIntegerLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified odata query has invalid real literal &apos;{0}&apos;..
        /// </summary>
        internal static string ODataExpressionParser_InvalidRealLiteral {
            get {
                return ResourceManager.GetString("ODataExpressionParser_InvalidRealLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified odata query has invalid &apos;{0}&apos; type creation expression..
        /// </summary>
        internal static string ODataExpressionParser_InvalidTypeCreation {
            get {
                return ResourceManager.GetString("ODataExpressionParser_InvalidTypeCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;(&apos; expected..
        /// </summary>
        internal static string ODataExpressionParser_OpenParenExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_OpenParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected real literal..
        /// </summary>
        internal static string ODataExpressionParser_RealLiteralExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_RealLiteralExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string literal..
        /// </summary>
        internal static string ODataExpressionParser_StringLiteralExpected {
            get {
                return ResourceManager.GetString("ODataExpressionParser_StringLiteralExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;substring&apos; requires 2 or 3 parameters..
        /// </summary>
        internal static string ODataExpressionParser_SubstringArgsCount {
            get {
                return ResourceManager.GetString("ODataExpressionParser_SubstringArgsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified odata query has syntax errors..
        /// </summary>
        internal static string ODataExpressionParser_SyntaxError {
            get {
                return ResourceManager.GetString("ODataExpressionParser_SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified odata query has unterminated string literal..
        /// </summary>
        internal static string ODataExpressionParser_UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("ODataExpressionParser_UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Microsoft Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}..
        /// </summary>
        internal static string Platform_AssemblyNotFound {
            get {
                return ResourceManager.GetString("Platform_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate the platform implementation of {0} from the assembly {1} due to the following error: {2}.
        /// </summary>
        internal static string Platform_InstantiationFailed {
            get {
                return ResourceManager.GetString("Platform_InstantiationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; is reserved and cannot be specified as a query parameter..
        /// </summary>
        internal static string Pull_Cannot_Use_Reserved_Key {
            get {
                return ResourceManager.GetString("Pull_Cannot_Use_Reserved_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid XML is required for any template without a raw header..
        /// </summary>
        internal static string Push_BodyTemplateMustBeXml {
            get {
                return ResourceManager.GetString("Push_BodyTemplateMustBeXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML must contain an XML node of Element type..
        /// </summary>
        internal static string Push_BodyTemplateMustContainElement {
            get {
                return ResourceManager.GetString("Push_BodyTemplateMustContainElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name conflicts with reserved name &apos;{0}&apos;..
        /// </summary>
        internal static string Push_ConflictWithReservedName {
            get {
                return ResourceManager.GetString("Push_ConflictWithReservedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push operation has failed. See the PushResult for details..
        /// </summary>
        internal static string Push_Failure {
            get {
                return ResourceManager.GetString("Push_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name cannot contain &quot;;&quot; or &quot;:&quot;..
        /// </summary>
        internal static string Push_InvalidTemplateName {
            get {
                return ResourceManager.GetString("Push_InvalidTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bodyTemplate is not in accepted XML format. The first node of the bodyTemplate should be Badge/Tile/Toast, except for the wns/raw template, which needs to be an valid XML..
        /// </summary>
        internal static string Push_NotSupportedXMLFormatAsBodyTemplateWin8 {
            get {
                return ResourceManager.GetString("Push_NotSupportedXMLFormatAsBodyTemplateWin8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags must not contain &apos;,&apos;..
        /// </summary>
        internal static string Push_TagNoCommas {
            get {
                return ResourceManager.GetString("Push_TagNoCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A delete operation on the item is already in the queue..
        /// </summary>
        internal static string SyncContext_DeletePending {
            get {
                return ResourceManager.GetString("SyncContext_DeletePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An insert operation on the item is already in the queue..
        /// </summary>
        internal static string SyncContext_DuplicateInsert {
            get {
                return ResourceManager.GetString("SyncContext_DuplicateInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is in inconsistent state in the local store. Please complete the pending sync by calling PushAsync()before deleting the item..
        /// </summary>
        internal static string SyncContext_InsertAttempted {
            get {
                return ResourceManager.GetString("SyncContext_InsertAttempted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SyncContext is not yet initialized..
        /// </summary>
        internal static string SyncContext_NotInitialized {
            get {
                return ResourceManager.GetString("SyncContext_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table cannot be purged because it has pending operations..
        /// </summary>
        internal static string SyncContext_PurgeOnDirtyTable {
            get {
                return ResourceManager.GetString("SyncContext_PurgeOnDirtyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update operation on the item is already in the queue..
        /// </summary>
        internal static string SyncContext_UpdatePending {
            get {
                return ResourceManager.GetString("SyncContext_UpdatePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been updated and cannot be cancelled..
        /// </summary>
        internal static string SyncError_OperationUpdated {
            get {
                return ResourceManager.GetString("SyncError_OperationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store is already initialized..
        /// </summary>
        internal static string SyncStore_AlreadyInitialized {
            get {
                return ResourceManager.GetString("SyncStore_AlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete error from the local store..
        /// </summary>
        internal static string SyncStore_FailedToDeleteError {
            get {
                return ResourceManager.GetString("SyncStore_FailedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete operation from the local store..
        /// </summary>
        internal static string SyncStore_FailedToDeleteOperation {
            get {
                return ResourceManager.GetString("SyncStore_FailedToDeleteOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read errors from the local store..
        /// </summary>
        internal static string SyncStore_FailedToLoadError {
            get {
                return ResourceManager.GetString("SyncStore_FailedToLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read the item from local store..
        /// </summary>
        internal static string SyncStore_FailedToReadItem {
            get {
                return ResourceManager.GetString("SyncStore_FailedToReadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update operation in the local store..
        /// </summary>
        internal static string SyncStore_FailedToUpdateOperation {
            get {
                return ResourceManager.GetString("SyncStore_FailedToUpdateOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the item in the local store..
        /// </summary>
        internal static string SyncStore_FailedToUpsertItem {
            get {
                return ResourceManager.GetString("SyncStore_FailedToUpsertItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store must be initialized before it can be used..
        /// </summary>
        internal static string SyncStore_NotInitialized {
            get {
                return ResourceManager.GetString("SyncStore_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to perform operation on local store..
        /// </summary>
        internal static string SyncStore_OperationFailed {
            get {
                return ResourceManager.GetString("SyncStore_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page must be called from the type &apos;{0}&apos;..
        /// </summary>
        internal static string WP8LoginPage_MustBeCalledFromAuthBroker {
            get {
                return ResourceManager.GetString("WP8LoginPage_MustBeCalledFromAuthBroker", resourceCulture);
            }
        }
    }
}
