//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.MobileServices.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Linq IQueryable Select() operation is not supported on the Windows Phone 7.5 platform..
        /// </summary>
        internal static string ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75 {
            get {
                return ResourceManager.GetString("ExpressionUtility_ProjectionNotSupportedOnWindowsPhone75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is not supported in the &apos;Where&apos; Mobile Services query expression &apos;{1}&apos;..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_MemberUnsupported {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_MemberUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operator &apos;{0}&apos; is not supported in the &apos;Where&apos; Mobile Services query expression &apos;{1}&apos;..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_OperatorUnsupported {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_OperatorUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not supported in a &apos;Where&apos; Mobile Services query expression..
        /// </summary>
        internal static string FilterBuildingExpressionVisitor_UnsupportedInWhereExpression {
            get {
                return ResourceManager.GetString("FilterBuildingExpressionVisitor_UnsupportedInWhereExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All message handlers except the last must be of the type &apos;{0}&apos;.
        /// </summary>
        internal static string HttpMessageHandlerExtensions_WrongHandlerType {
            get {
                return ResourceManager.GetString("HttpMessageHandlerExtensions_WrongHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An application setting name must be provided. Null, empty or whitespace only names are not allowed..
        /// </summary>
        internal static string IApplicationStorage_NullOrWhitespaceSettingName {
            get {
                return ResourceManager.GetString("IApplicationStorage_NullOrWhitespaceSettingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication was cancelled by the user..
        /// </summary>
        internal static string IAuthenticationBroker_AuthenticationCanceled {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_AuthenticationCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed with HTTP response code {0}..
        /// </summary>
        internal static string IAuthenticationBroker_AuthenticationFailed {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of the authentication response..
        /// </summary>
        internal static string IAuthenticationBroker_InvalidLoginResponse {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_InvalidLoginResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed: {0}.
        /// </summary>
        internal static string IAuthenticationBroker_LoginFailed {
            get {
                return ResourceManager.GetString("IAuthenticationBroker_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null, empty or only whitespace..
        /// </summary>
        internal static string MobileServiceClient_EmptyArgument {
            get {
                return ResourceManager.GetString("MobileServiceClient_EmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be completed.  ({0}).
        /// </summary>
        internal static string MobileServiceClient_ErrorMessage {
            get {
                return ResourceManager.GetString("MobileServiceClient_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;InnerHandler&apos; property of the delegating handler must be null..
        /// </summary>
        internal static string MobileServiceClient_InnerHandlerMustBeNull {
            get {
                return ResourceManager.GetString("MobileServiceClient_InnerHandlerMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server did not provide a response with the expected content..
        /// </summary>
        internal static string MobileServiceClient_NoResponseContent {
            get {
                return ResourceManager.GetString("MobileServiceClient_NoResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading of more items already in process..
        /// </summary>
        internal static string MobileServiceCollection_LoadInProcess {
            get {
                return ResourceManager.GetString("MobileServiceCollection_LoadInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has an integer id member and therefore can not have any members with the system property attribute &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_IntegerIdTypeWithSystemPropertyAttributes", resourceCulture);
            }
        }

        ///   Looks up a localized string similar to Failed to incrementally load more items of type &apos;{0}&apos;. See the inner exception for details..
        /// </summary>
        internal static string MobileServiceCollection_IncrementalLoadingFailed {
            get {
                return ResourceManager.GetString("MobileServiceCollection_IncrementalLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &apos;{0}&apos; member found on type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_MemberNotFound {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A member can only have one system property attribute. The member &apos;{0}&apos; on type &apos;{1}&apos; has system property attributes &apos;{2}&apos; and &apos;{3}&apos;. .
        /// </summary>
        internal static string MobileServiceContractResolver_MultipleSystemPropertyAttributes {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_MultipleSystemPropertyAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for member {1} is outside the valid range for numeric columns..
        /// </summary>
        internal static string MobileServiceContractResolver_NumberOutOfRange {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_NumberOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one member may have the property name &apos;{0}&apos; (regardless of casing) on type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceContractResolver_SamePropertyName {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_SamePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not have a DataContractAttribute, but the type derives from the type &apos;{1}&apos;, which does have a DataContractAttribute. If a type has a DataContractAttribute, any type that derives from that type must also have a DataContractAttribute..
        /// </summary>
        internal static string MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_TypeNoDataContractButBaseWithDataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; has one or members with a DataMemberAttribute, but the type itself does not have a DataContractAttribute. Use the Newtonsoft.Json.JsonPropertyAttribute in place of the DataMemberAttribute and set the PropertyName to the desired name..
        /// </summary>
        internal static string MobileServiceContractResolver_TypeWithDataMemberButNoDataContract {
            get {
                return ResourceManager.GetString("MobileServiceContractResolver_TypeWithDataMemberButNoDataContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}.ContractResolver&apos; must be set to an instance of the &apos;{1}&apos; class or a class that inherits from the &apos;{1}&apos; class..
        /// </summary>
        internal static string MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver {
            get {
                return ResourceManager.GetString("MobileServiceJsonSerializerSettings_NullOrInvalidContractResolver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} does not support reading JSON..
        /// </summary>
        internal static string MobileServicePrecisionCheckConverter_ReadNotSupported {
            get {
                return ResourceManager.GetString("MobileServicePrecisionCheckConverter_ReadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start a login operation because login is already in progress..
        /// </summary>
        internal static string MobileServicesAuthentication_LoginAlreadyInProgress {
            get {
                return ResourceManager.GetString("MobileServicesAuthentication_LoginAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The casing of the &apos;{0}&apos; property is invalid..
        /// </summary>
        internal static string MobileServiceSerializer_IdCasingIncorrect {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdCasingIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} member not found..
        /// </summary>
        internal static string MobileServiceSerializer_IdNotFound {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might be affected by Mobile Services latest changes to support string Ids. For more details: http://go.microsoft.com/fwlink/?LinkId=330396.
        /// </summary>
        internal static string MobileServiceSerializer_IdTypeMismatch {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_IdTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The integer id &apos;{0}&apos; is not a positive integer value..
        /// </summary>
        internal static string MobileServiceSerializer_InvalidIntegerId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_InvalidIntegerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string id &apos;{0}&apos; is invalid. An id must not contain any control characters or the characters &quot;,+,?,\,/`..
        /// </summary>
        internal static string MobileServiceSerializer_InvalidStringId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_InvalidStringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id parameter type &apos;{0}&apos; is invalid for looking up items of type &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceSerializer_LookupInvalidIdType {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_LookupInvalidIdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The id can not be null or an empty string..
        /// </summary>
        internal static string MobileServiceSerializer_NullOrEmptyStringId {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_NullOrEmptyStringId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string id &apos;{0}&apos; is longer than the max string id length of {1} characters..
        /// </summary>
        internal static string MobileServiceSerializer_StringIdTooLong {
            get {
                return ResourceManager.GetString("MobileServiceSerializer_StringIdTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete if the {0} member is set to a default value..
        /// </summary>
        internal static string MobileServiceTable_DeleteWithoutId {
            get {
                return ResourceManager.GetString("MobileServiceTable_DeleteWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get an array from response {0}..
        /// </summary>
        internal static string MobileServiceTable_ExpectedArray {
            get {
                return ResourceManager.GetString("MobileServiceTable_ExpectedArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert if the {0} member is already set..
        /// </summary>
        internal static string MobileServiceTable_InsertWithExistingId {
            get {
                return ResourceManager.GetString("MobileServiceTable_InsertWithExistingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get object from response {0}..
        /// </summary>
        internal static string MobileServiceTable_NotSingleObject {
            get {
                return ResourceManager.GetString("MobileServiceTable_NotSingleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update if the {0} member is set to a default value..
        /// </summary>
        internal static string MobileServiceTable_UpdateWithoutId {
            get {
                return ResourceManager.GetString("MobileServiceTable_UpdateWithoutId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Mobile Services query expressions must consist of members only, not &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_MembersOnlyInExpression {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_MembersOnlyInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; Mobile Services query expressions must consist of a single integer, not &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_SingleIntegerOnly {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_SingleIntegerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{1}&apos; is not a supported &apos;{0}&apos; Mobile Services query expression..
        /// </summary>
        internal static string MobileServiceTableQueryTranslator_UnsupportedExpression {
            get {
                return ResourceManager.GetString("MobileServiceTableQueryTranslator_UnsupportedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize value {0} into &apos;{1}.{2}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_CannotDeserializeValue {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_CannotDeserializeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize type &apos;{0}&apos; because the JSON object did not have required member(s) &apos;{1}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_MissingRequiredMember {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_MissingRequiredMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a JSON object to deserialize, not &apos;{0}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_NeedObject {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_NeedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize member &apos;{0}&apos; of type &apos;{1}&apos; declared on type &apos;{2}&apos;..
        /// </summary>
        internal static string MobileServiceTableSerializer_UnknownType {
            get {
                return ResourceManager.GetString("MobileServiceTableSerializer_UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid user-defined query string parameter. User-defined query string parameters must not begin with a \&apos;$\&apos;..
        /// </summary>
        internal static string MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign {
            get {
                return ResourceManager.GetString("MobileServiceTableUrlBuilder_InvalidParameterBeginsWithDollarSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The assembly {0} does not define a type that implements the {1} interface..
        /// </summary>
        internal static string Platform_AssemblyDidNotHaveType {
            get {
                return ResourceManager.GetString("Platform_AssemblyDidNotHaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party provider authentication requires user interface components and is not supported with the platform-specific assembly {0}. To authenticate users with a third-party provider, ensure that the project references the platform-specific UI assembly {0}.UI..
        /// </summary>
        internal static string Platform_AssemblyDoesNotSupportLogin {
            get {
                return ResourceManager.GetString("Platform_AssemblyDoesNotSupportLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows Azure Mobile Services assembly for the current platform was not found. Ensure that the current project references both {0} and the following platform-specific assembly: {1}..
        /// </summary>
        internal static string Platform_AssemblyNotFound {
            get {
                return ResourceManager.GetString("Platform_AssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to instantiate the platform implemenation of {0} from the assembly {1} due to the following error: {2}.
        /// </summary>
        internal static string Platform_InstantiationFailed {
            get {
                return ResourceManager.GetString("Platform_InstantiationFailed", resourceCulture);
            }
        }
    }
}
