//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.MobileServices.Caching {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.MobileServices.Caching.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value cannot be specified for reserved property name &apos;{0}&apos;..
        /// </summary>
        public static string CannotInsertReservedProperty {
            get {
                return ResourceManager.GetString("CannotInsertReservedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; or &apos;,&apos; expected.
        /// </summary>
        public static string CloseParenOrCommaExpected {
            get {
                return ResourceManager.GetString("CloseParenOrCommaExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;)&apos; or operator expected.
        /// </summary>
        public static string CloseParenOrOperatorExpected {
            get {
                return ResourceManager.GetString("CloseParenOrOperatorExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection &apos;{0}&apos; does not exist..
        /// </summary>
        public static string CollectionDoesNotExist {
            get {
                return ResourceManager.GetString("CollectionDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delete operation failed..
        /// </summary>
        public static string DeleteOperationFailed {
            get {
                return ResourceManager.GetString("DeleteOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digit expected.
        /// </summary>
        public static string DigitExpected {
            get {
                return ResourceManager.GetString("DigitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression expected.
        /// </summary>
        public static string ExpressionExpected {
            get {
                return ResourceManager.GetString("ExpressionExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier expected.
        /// </summary>
        public static string IdentifierExpected {
            get {
                return ResourceManager.GetString("IdentifierExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid hexadecimal literal.
        /// </summary>
        public static string InvalidHexLiteral {
            get {
                return ResourceManager.GetString("InvalidHexLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer literal &apos;{0}&apos;.
        /// </summary>
        public static string InvalidIntegerLiteral {
            get {
                return ResourceManager.GetString("InvalidIntegerLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query specified. {0}.
        /// </summary>
        public static string InvalidQuerySpecified {
            get {
                return ResourceManager.GetString("InvalidQuerySpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid real literal &apos;{0}&apos;.
        /// </summary>
        public static string InvalidRealLiteral {
            get {
                return ResourceManager.GetString("InvalidRealLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid &apos;{0}&apos; type creation expression.
        /// </summary>
        public static string InvalidTypeCreationExpression {
            get {
                return ResourceManager.GetString("InvalidTypeCreationExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When specified in the body, &apos;id&apos; must be a number and must match the id specified in the url..
        /// </summary>
        public static string InvalidUpdateIdSpecified {
            get {
                return ResourceManager.GetString("InvalidUpdateIdSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert a null value for new property &apos;{0}&apos;.
        /// </summary>
        public static string NewColumnNullValueNotAllowed {
            get {
                return ResourceManager.GetString("NewColumnNullValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applicable method &apos;{0}&apos; exists in type &apos;{1}&apos;.
        /// </summary>
        public static string NoApplicableMethod {
            get {
                return ResourceManager.GetString("NoApplicableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;(&apos; expected.
        /// </summary>
        public static string OpenParenExpected {
            get {
                return ResourceManager.GetString("OpenParenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT {0}.
        /// </summary>
        public static string PagingQueryTemplate {
            get {
                return ResourceManager.GetString("PagingQueryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (at index {1}).
        /// </summary>
        public static string ParseExceptionFormat {
            get {
                return ResourceManager.GetString("ParseExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for &apos;{0}&apos; must be an integer..
        /// </summary>
        public static string SkipTopMustBeInteger {
            get {
                return ResourceManager.GetString("SkipTopMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM (.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ROW_NUMBER() OVER (ORDER BY {1}) AS [ROW_NUMBER], {2}.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM {3}.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE {4}.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ) AS [t1].
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHERE [t1].[ROW_NUMBER] BETWEEN {5} + 1 AND {5} + {6}.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER BY [t1].[ROW_NUMBER].
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error.
        /// </summary>
        public static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to map type &apos;{0}&apos; to a SQL type..
        /// </summary>
        public static string UnableToMapToSqlType {
            get {
                return ResourceManager.GetString("UnableToMapToSqlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown identifier &apos;{0}&apos;.
        /// </summary>
        public static string UnknownIdentifier {
            get {
                return ResourceManager.GetString("UnknownIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterminated string literal.
        /// </summary>
        public static string UnterminatedStringLiteral {
            get {
                return ResourceManager.GetString("UnterminatedStringLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update operation failed..
        /// </summary>
        public static string UpdateOperationFailed {
            get {
                return ResourceManager.GetString("UpdateOperationFailed", resourceCulture);
            }
        }
    }
}
